// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `spectrum.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef _____ESenseInterfaces__spectrum_h__
#define _____ESenseInterfaces__spectrum_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/BuiltinSequences.h>
#include <sync.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Electrosense
{

class SpectrumSegment;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Electrosense::SpectrumSegment>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Electrosense::SpectrumSegment*);

class Spectrum;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Electrosense::Spectrum>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Electrosense::Spectrum*);

}

}

namespace Electrosense
{

class SpectrumSegment;
::Ice::Object* upCast(::Electrosense::SpectrumSegment*);
typedef ::IceInternal::Handle< ::Electrosense::SpectrumSegment> SpectrumSegmentPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Electrosense::SpectrumSegment> SpectrumSegmentPrx;
void __patch(SpectrumSegmentPtr&, const ::Ice::ObjectPtr&);

class Spectrum;
::Ice::Object* upCast(::Electrosense::Spectrum*);
typedef ::IceInternal::Handle< ::Electrosense::Spectrum> SpectrumPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Electrosense::Spectrum> SpectrumPrx;
void __patch(SpectrumPtr&, const ::Ice::ObjectPtr&);

}

namespace Electrosense
{

class Callback_Spectrum_push_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Spectrum_push_Base> Callback_Spectrum_pushPtr;

}

namespace IceProxy
{

namespace Electrosense
{

class SpectrumSegment : virtual public ::IceProxy::Ice::Object
{
public:
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_secure(bool __secure) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_twoway() const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_oneway() const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_batchOneway() const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_datagram() const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_batchDatagram() const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_compress(bool __compress) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_timeout(int __timeout) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<SpectrumSegment> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<SpectrumSegment*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class Spectrum : virtual public ::IceProxy::Ice::Object
{
public:

    void push(const ::Electrosense::SpectrumSegmentPtr& __p_segment)
    {
        push(__p_segment, 0);
    }
    void push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::Ice::Context& __ctx)
    {
        push(__p_segment, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_push(__p_segment, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_push(__p_segment, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_push(__p_segment, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_push(__p_segment, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment)
    {
        return begin_push(__p_segment, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::Ice::Context& __ctx)
    {
        return begin_push(__p_segment, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_push(__p_segment, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_push(__p_segment, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::Electrosense::Callback_Spectrum_pushPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_push(__p_segment, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::Ice::Context& __ctx, const ::Electrosense::Callback_Spectrum_pushPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_push(__p_segment, &__ctx, __del, __cookie);
    }

    void end_push(const ::Ice::AsyncResultPtr&);
    
private:

    void push(const ::Electrosense::SpectrumSegmentPtr&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_push(const ::Electrosense::SpectrumSegmentPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Spectrum> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_secure(bool __secure) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_twoway() const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_oneway() const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_batchOneway() const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_datagram() const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_batchDatagram() const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_compress(bool __compress) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Spectrum> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Spectrum*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace Electrosense
{

class SpectrumSegment : virtual public ::Ice::Object, public ::IceInternal::GCObject
{
public:

    typedef SpectrumSegmentPrx ProxyType;
    typedef SpectrumSegmentPtr PointerType;

    SpectrumSegment()
    {
    }

    SpectrumSegment(::Ice::Long __ice_sensorID, const ::Electrosense::TimePtr& __ice_timestamp, ::Ice::Long __ice_centerFrequency, ::Ice::Long __ice_samplingRate, ::Ice::Long __ice_samplesSize, const ::Ice::ByteSeq& __ice_samples) :
        sensorID(__ice_sensorID),
        timestamp(__ice_timestamp),
        centerFrequency(__ice_centerFrequency),
        samplingRate(__ice_samplingRate),
        samplesSize(__ice_samplesSize),
        samples(__ice_samples)
    {
    }

    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void __gcVisitMembers(::IceInternal::GCVisitor&);

    static ::Ice::ObjectFactoryPtr ice_factory();

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;

public:

    ::Ice::Long sensorID;

    ::Electrosense::TimePtr timestamp;

    ::Ice::Long centerFrequency;

    ::Ice::Long samplingRate;

    ::Ice::Long samplesSize;

    ::Ice::ByteSeq samples;
protected:

    virtual ~SpectrumSegment() {}

friend class SpectrumSegment__staticInit;
};
#if !defined(_MSC_VER) || (_MSC_VER < 1900)
//
// COMPILERFIX: Visual Studio 2015 update 1 fails to access
// the proected destructor from a friend class.
//

class SpectrumSegment__staticInit
{
public:

    ::Electrosense::SpectrumSegment _init;
};

static SpectrumSegment__staticInit _SpectrumSegment_init;
#else
static auto _SpectrumSegment_init = ::Electrosense::SpectrumSegment::ice_factory;
#endif

inline bool operator==(const SpectrumSegment& l, const SpectrumSegment& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const SpectrumSegment& l, const SpectrumSegment& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class Spectrum : virtual public ::Ice::Object
{
public:

    typedef SpectrumPrx ProxyType;
    typedef SpectrumPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void push(const ::Electrosense::SpectrumSegmentPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___push(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const Spectrum& l, const Spectrum& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Spectrum& l, const Spectrum& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Electrosense
{

template<class T>
class CallbackNC_Spectrum_push : public Callback_Spectrum_push_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Spectrum_push(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Spectrum_pushPtr
newCallback_Spectrum_push(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Spectrum_push<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Spectrum_pushPtr
newCallback_Spectrum_push(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Spectrum_push<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Spectrum_pushPtr
newCallback_Spectrum_push(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Spectrum_push<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Spectrum_pushPtr
newCallback_Spectrum_push(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Spectrum_push<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Spectrum_push : public Callback_Spectrum_push_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Spectrum_push(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Spectrum_pushPtr
newCallback_Spectrum_push(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Spectrum_push<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Spectrum_pushPtr
newCallback_Spectrum_push(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Spectrum_push<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Spectrum_pushPtr
newCallback_Spectrum_push(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Spectrum_push<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Spectrum_pushPtr
newCallback_Spectrum_push(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Spectrum_push<T, CT>(instance, 0, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
