// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `spectrum.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <spectrum.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Electrosense__Spectrum__push_name = "push";

}
::IceProxy::Ice::Object* ::IceProxy::Electrosense::upCast(::IceProxy::Electrosense::SpectrumSegment* p) { return p; }

void
::IceProxy::Electrosense::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Electrosense::SpectrumSegment>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Electrosense::SpectrumSegment;
        v->__copyFrom(proxy);
    }
}

const ::std::string&
IceProxy::Electrosense::SpectrumSegment::ice_staticId()
{
    return ::Electrosense::SpectrumSegment::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::Electrosense::SpectrumSegment::__newInstance() const
{
    return new SpectrumSegment;
}
::IceProxy::Ice::Object* ::IceProxy::Electrosense::upCast(::IceProxy::Electrosense::Spectrum* p) { return p; }

void
::IceProxy::Electrosense::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Electrosense::Spectrum>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Electrosense::Spectrum;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Electrosense::Spectrum::push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __Electrosense__Spectrum__push_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_segment);
        __os->writePendingObjects();
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::Electrosense::Spectrum::begin_push(const ::Electrosense::SpectrumSegmentPtr& __p_segment, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Electrosense__Spectrum__push_name, __del, __cookie);
    try
    {
        __result->prepare(__Electrosense__Spectrum__push_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_segment);
        __os->writePendingObjects();
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::Electrosense::Spectrum::end_push(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Electrosense__Spectrum__push_name);
}

const ::std::string&
IceProxy::Electrosense::Spectrum::ice_staticId()
{
    return ::Electrosense::Spectrum::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::Electrosense::Spectrum::__newInstance() const
{
    return new Spectrum;
}

::Ice::Object* Electrosense::upCast(::Electrosense::SpectrumSegment* p) { return p; }

#if defined(_MSC_VER) && (_MSC_VER >= 1900)
#   pragma warning(push)
#   pragma warning(disable:4589)
#endif
::Ice::ObjectPtr
Electrosense::SpectrumSegment::ice_clone() const
{
    ::Ice::Object* __p = new SpectrumSegment(*this);
    return __p;
}
#if defined(_MSC_VER) && (_MSC_VER >= 1900)
#   pragma warning(pop)
#endif

namespace
{
const ::std::string __Electrosense__SpectrumSegment_ids[2] =
{
    "::Electrosense::SpectrumSegment",
    "::Ice::Object"
};

}

bool
Electrosense::SpectrumSegment::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Electrosense__SpectrumSegment_ids, __Electrosense__SpectrumSegment_ids + 2, _s);
}

::std::vector< ::std::string>
Electrosense::SpectrumSegment::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Electrosense__SpectrumSegment_ids[0], &__Electrosense__SpectrumSegment_ids[2]);
}

const ::std::string&
Electrosense::SpectrumSegment::ice_id(const ::Ice::Current&) const
{
    return __Electrosense__SpectrumSegment_ids[0];
}

const ::std::string&
Electrosense::SpectrumSegment::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Electrosense::SpectrumSegment";
    return typeId;
#else
    return __Electrosense__SpectrumSegment_ids[0];
#endif
}

void
Electrosense::SpectrumSegment::__gcVisitMembers(::IceInternal::GCVisitor& _v)
{
    if(timestamp)
    {
        if((::Electrosense::upCast(timestamp.get())->__gcVisit(_v)))
        {
            timestamp = 0;
        }
    }
}

void
Electrosense::SpectrumSegment::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->write(sensorID);
    __os->write(timestamp);
    __os->write(centerFrequency);
    __os->write(samplingRate);
    __os->write(samplesSize);
    __os->write(samples);
    __os->endWriteSlice();
}

void
Electrosense::SpectrumSegment::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->read(sensorID);
    __is->read(timestamp);
    __is->read(centerFrequency);
    __is->read(samplingRate);
    __is->read(samplesSize);
    __is->read(samples);
    __is->endReadSlice();
}

namespace
{

const ::IceInternal::DefaultObjectFactoryInit< ::Electrosense::SpectrumSegment> __Electrosense__SpectrumSegment_init("::Electrosense::SpectrumSegment");
}

::Ice::ObjectFactoryPtr
Electrosense::SpectrumSegment::ice_factory()
{
    return ::IceInternal::factoryTable->getObjectFactory(::Electrosense::SpectrumSegment::ice_staticId());
}

void 
Electrosense::__patch(SpectrumSegmentPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Electrosense::SpectrumSegmentPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Electrosense::SpectrumSegment::ice_staticId(), v);
    }
}

::Ice::Object* Electrosense::upCast(::Electrosense::Spectrum* p) { return p; }

namespace
{
const ::std::string __Electrosense__Spectrum_ids[2] =
{
    "::Electrosense::Spectrum",
    "::Ice::Object"
};

}

bool
Electrosense::Spectrum::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Electrosense__Spectrum_ids, __Electrosense__Spectrum_ids + 2, _s);
}

::std::vector< ::std::string>
Electrosense::Spectrum::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Electrosense__Spectrum_ids[0], &__Electrosense__Spectrum_ids[2]);
}

const ::std::string&
Electrosense::Spectrum::ice_id(const ::Ice::Current&) const
{
    return __Electrosense__Spectrum_ids[0];
}

const ::std::string&
Electrosense::Spectrum::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Electrosense::Spectrum";
    return typeId;
#else
    return __Electrosense__Spectrum_ids[0];
#endif
}

::Ice::DispatchStatus
Electrosense::Spectrum::___push(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Electrosense::SpectrumSegmentPtr __p_segment;
    __is->read(__p_segment);
    __is->readPendingObjects();
    __inS.endReadParams();
    push(__p_segment, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Electrosense__Spectrum_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "push"
};

}

::Ice::DispatchStatus
Electrosense::Spectrum::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Electrosense__Spectrum_all, __Electrosense__Spectrum_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Electrosense__Spectrum_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___push(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Electrosense::Spectrum::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Electrosense::Spectrum::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Electrosense::__patch(SpectrumPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Electrosense::SpectrumPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Electrosense::Spectrum::ice_staticId(), v);
    }
}
